### ISSUE TITLE
三级审批人可以改成选填嘛

### ISSUE THREAD

**Issue by Fortune857** [Rinfair-CSP-A016/escape-from-school#1]
我们学校只要二级审批就行了，还有就是目的地显示好像有bug，有时会显示不出，谢谢了

**Comment by Rinfair** [comment]
二级审批人和三级审批人都是默认选填，只有当二者的第一项被填入时才要求必填

**Comment by Rinfair** [comment]
我测试了一下，目的地等内容确实有你提出的情况，会在下个版本进行修复

**Comment by Rinfair** [comment]
Bug fixed due to ac5aa0b and 73521f8
已修复以上情况，请注意，若不存在三级审批人/二级审批人，请对三级审批人/二级审批人有关的所有项均留空不填。
